version: '2'
services:
  db:
    image: postgres:alpine
    volumes:
      - ./postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
  adm:
    image: dpage/pgadmin4
    volumes:
      - ./pgadmin:/var/lib/pgadmin/storage
    ports:
      - "80:80"
      - "443:443"
    environment:
       PGADMIN_DEFAULT_EMAIL: admin
       PGADMIN_DEFAULT_PASSWORD: admin
