apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - name: pgql
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:alpine
          env:
            - name: POSTGRES_USER
              value: dev
            - name: POSTGRES_PASSWORD
              value: dev
            - name: POSTGRES_DB
              value: dev
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pg-data
      volumes:
        - name: pg-data
          hostPath:
            path: /tmp
            type: DirectoryOrCreate
