apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: dev
  POSTGRES_USER: dev
  POSTGRES_PASSWORD: dev
  PGDATA: /var/lib/postgresql/data/pgdata
